### ISSUE TITLE
魔镜使用

### ISSUE THREAD

**Issue by Franklincon** [weyo/MagicMirror#1]
怎么编译程序老哥？如何使用app能说详细点吗。谢谢

**Comment by weyo** [comment]
编译方法在README的“使用方法”里有说明，Tomcat 的war包要使用Maven，然后手机APP可以在 https://pan.baidu.com/s/1kV0RLfL 下载，使用也很简单，在后台Tomcat程序开启之后，打开APP，先进入左下角的设置页设置好服务器地址，然后就可以返回点击语音按钮说话了
