### ISSUE TITLE
运行问题

### ISSUE THREAD

**Issue by DeLei33534** [weyo/MagicMirror#2]
您好，请问一下在程序编译后除了左上角的时间模块外，其它模块均不能显示，是因为什么问题？谢谢！

**Comment by weyo** [comment]
建议开发者模式查一下问题看看，很久没更新了，有些接口服务可能也不提供了

**Comment by DeLei33534** [comment]
> 建议开发者模式查一下问题看看，很久没更新了，有些接口服务可能也不提供了

好的，谢谢
